# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtDesignerGUI/GUI.ui'
#
# Created: Sat Aug  2 12:37:39 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 662)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.devTeam = QtGui.QLabel(self.centralwidget)
        self.devTeam.setObjectName("devTeam")
        self.verticalLayout.addWidget(self.devTeam)
        self.versionGUI = QtGui.QLabel(self.centralwidget)
        self.versionGUI.setObjectName("versionGUI")
        self.verticalLayout.addWidget(self.versionGUI)
        self.tabManager = QtGui.QTabWidget(self.centralwidget)
        self.tabManager.setUsesScrollButtons(False)
        self.tabManager.setObjectName("tabManager")
        self.accountManagerTab = QtGui.QWidget()
        self.accountManagerTab.setObjectName("accountManagerTab")
        self.tabAccountManager = QtGui.QTabWidget(self.accountManagerTab)
        self.tabAccountManager.setGeometry(QtCore.QRect(10, 10, 771, 491))
        self.tabAccountManager.setTabPosition(QtGui.QTabWidget.West)
        self.tabAccountManager.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabAccountManager.setIconSize(QtCore.QSize(64, 64))
        self.tabAccountManager.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabAccountManager.setObjectName("tabAccountManager")
        self.socialManagerTab = QtGui.QWidget()
        self.socialManagerTab.setObjectName("socialManagerTab")
        self.clientListLabel = QtGui.QLabel(self.socialManagerTab)
        self.clientListLabel.setGeometry(QtCore.QRect(10, 10, 62, 16))
        self.clientListLabel.setObjectName("clientListLabel")
        self.soccialAccountGroup = QtGui.QGroupBox(self.socialManagerTab)
        self.soccialAccountGroup.setGeometry(QtCore.QRect(240, 10, 431, 431))
        self.soccialAccountGroup.setObjectName("soccialAccountGroup")
        self.editBt = QtGui.QPushButton(self.soccialAccountGroup)
        self.editBt.setGeometry(QtCore.QRect(10, 370, 201, 32))
        self.editBt.setObjectName("editBt")
        self.removeBt = QtGui.QPushButton(self.soccialAccountGroup)
        self.removeBt.setEnabled(False)
        self.removeBt.setGeometry(QtCore.QRect(220, 370, 211, 32))
        self.removeBt.setObjectName("removeBt")
        self.gridLayoutWidget = QtGui.QWidget(self.soccialAccountGroup)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 421, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.linkedinCk = QtGui.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linkedinCk.sizePolicy().hasHeightForWidth())
        self.linkedinCk.setSizePolicy(sizePolicy)
        self.linkedinCk.setText("")
        self.linkedinCk.setObjectName("linkedinCk")
        self.gridLayout.addWidget(self.linkedinCk, 3, 0, 1, 1)
        self.googleLabel_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.googleLabel_2.setObjectName("googleLabel_2")
        self.gridLayout.addWidget(self.googleLabel_2, 5, 1, 1, 1)
        self.facebookLabel_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.facebookLabel_2.setObjectName("facebookLabel_2")
        self.gridLayout.addWidget(self.facebookLabel_2, 2, 1, 1, 1)
        self.youtubeCk = QtGui.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.youtubeCk.sizePolicy().hasHeightForWidth())
        self.youtubeCk.setSizePolicy(sizePolicy)
        self.youtubeCk.setText("")
        self.youtubeCk.setObjectName("youtubeCk")
        self.gridLayout.addWidget(self.youtubeCk, 4, 0, 1, 1)
        self.youtubeText_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.youtubeText_2.setEnabled(False)
        self.youtubeText_2.setObjectName("youtubeText_2")
        self.gridLayout.addWidget(self.youtubeText_2, 4, 2, 1, 1)
        self.linkedinText_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.linkedinText_2.setEnabled(False)
        self.linkedinText_2.setObjectName("linkedinText_2")
        self.gridLayout.addWidget(self.linkedinText_2, 3, 2, 1, 1)
        self.pinterestLabel_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.pinterestLabel_2.setMinimumSize(QtCore.QSize(100, 0))
        self.pinterestLabel_2.setObjectName("pinterestLabel_2")
        self.gridLayout.addWidget(self.pinterestLabel_2, 9, 1, 1, 1)
        self.pinterestCk = QtGui.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pinterestCk.sizePolicy().hasHeightForWidth())
        self.pinterestCk.setSizePolicy(sizePolicy)
        self.pinterestCk.setText("")
        self.pinterestCk.setObjectName("pinterestCk")
        self.gridLayout.addWidget(self.pinterestCk, 9, 0, 1, 1)
        self.youtubeLabel_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.youtubeLabel_2.setObjectName("youtubeLabel_2")
        self.gridLayout.addWidget(self.youtubeLabel_2, 4, 1, 1, 1)
        self.twitterLabel_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.twitterLabel_2.setObjectName("twitterLabel_2")
        self.gridLayout.addWidget(self.twitterLabel_2, 0, 1, 1, 1)
        self.twitterText_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.twitterText_2.setEnabled(False)
        self.twitterText_2.setObjectName("twitterText_2")
        self.gridLayout.addWidget(self.twitterText_2, 0, 2, 1, 1)
        self.facebookText_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.facebookText_2.setEnabled(False)
        self.facebookText_2.setObjectName("facebookText_2")
        self.gridLayout.addWidget(self.facebookText_2, 2, 2, 1, 1)
        self.googleText_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.googleText_2.setEnabled(False)
        self.googleText_2.setObjectName("googleText_2")
        self.gridLayout.addWidget(self.googleText_2, 5, 2, 1, 1)
        self.pinterestText_2 = QtGui.QLineEdit(self.gridLayoutWidget)
        self.pinterestText_2.setEnabled(False)
        self.pinterestText_2.setObjectName("pinterestText_2")
        self.gridLayout.addWidget(self.pinterestText_2, 9, 2, 1, 1)
        self.facebookCk = QtGui.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.facebookCk.sizePolicy().hasHeightForWidth())
        self.facebookCk.setSizePolicy(sizePolicy)
        self.facebookCk.setText("")
        self.facebookCk.setObjectName("facebookCk")
        self.gridLayout.addWidget(self.facebookCk, 2, 0, 1, 1)
        self.googleCk = QtGui.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.googleCk.sizePolicy().hasHeightForWidth())
        self.googleCk.setSizePolicy(sizePolicy)
        self.googleCk.setText("")
        self.googleCk.setObjectName("googleCk")
        self.gridLayout.addWidget(self.googleCk, 5, 0, 1, 1)
        self.linkedinLabel_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.linkedinLabel_2.setObjectName("linkedinLabel_2")
        self.gridLayout.addWidget(self.linkedinLabel_2, 3, 1, 1, 1)
        self.twitterCk = QtGui.QCheckBox(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twitterCk.sizePolicy().hasHeightForWidth())
        self.twitterCk.setSizePolicy(sizePolicy)
        self.twitterCk.setObjectName("twitterCk")
        self.gridLayout.addWidget(self.twitterCk, 0, 0, 1, 1)
        self.clientListWidget = QtGui.QListWidget(self.socialManagerTab)
        self.clientListWidget.setGeometry(QtCore.QRect(10, 30, 221, 341))
        self.clientListWidget.setObjectName("clientListWidget")
        self.deleteClientButton = QtGui.QPushButton(self.socialManagerTab)
        self.deleteClientButton.setGeometry(QtCore.QRect(10, 390, 211, 31))
        self.deleteClientButton.setObjectName("deleteClientButton")
        self.addClientButton = QtGui.QPushButton(self.socialManagerTab)
        self.addClientButton.setGeometry(QtCore.QRect(390, 0, 161, 31))
        self.addClientButton.setObjectName("addClientButton")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/social.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabAccountManager.addTab(self.socialManagerTab, icon, "")
        self.tabManager.addTab(self.accountManagerTab, "")
        self.followersGetter = QtGui.QWidget()
        self.followersGetter.setObjectName("followersGetter")
        self.tableView = QtGui.QTableView(self.followersGetter)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 791, 411))
        self.tableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.fetchBt = QtGui.QPushButton(self.followersGetter)
        self.fetchBt.setGeometry(QtCore.QRect(280, 430, 291, 61))
        self.fetchBt.setObjectName("fetchBt")
        self.tabManager.addTab(self.followersGetter, "")
        self.verticalLayout.addWidget(self.tabManager)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 20))
        self.menubar.setObjectName("menubar")
        self.menuArchive = QtGui.QMenu(self.menubar)
        self.menuArchive.setObjectName("menuArchive")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_accounts_data_file = QtGui.QAction(MainWindow)
        self.actionOpen_accounts_data_file.setObjectName("actionOpen_accounts_data_file")
        self.actionDevelopers = QtGui.QAction(MainWindow)
        self.actionDevelopers.setObjectName("actionDevelopers")
        self.actionSocial_Manager_GUI = QtGui.QAction(MainWindow)
        self.actionSocial_Manager_GUI.setObjectName("actionSocial_Manager_GUI")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuArchive.addAction(self.actionOpen_accounts_data_file)
        self.menuArchive.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionSocial_Manager_GUI)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionDevelopers)
        self.menubar.addAction(self.menuArchive.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabManager.setCurrentIndex(0)
        self.tabAccountManager.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Social Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.devTeam.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">BSoD Software</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.versionGUI.setText(QtGui.QApplication.translate("MainWindow", "v0.17", None, QtGui.QApplication.UnicodeUTF8))
        self.clientListLabel.setText(QtGui.QApplication.translate("MainWindow", "Client list", None, QtGui.QApplication.UnicodeUTF8))
        self.soccialAccountGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Social account data", None, QtGui.QApplication.UnicodeUTF8))
        self.editBt.setText(QtGui.QApplication.translate("MainWindow", "Edit info", None, QtGui.QApplication.UnicodeUTF8))
        self.removeBt.setText(QtGui.QApplication.translate("MainWindow", "Remove accounts", None, QtGui.QApplication.UnicodeUTF8))
        self.googleLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Google+", None, QtGui.QApplication.UnicodeUTF8))
        self.facebookLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Facebook", None, QtGui.QApplication.UnicodeUTF8))
        self.pinterestLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Pinterest", None, QtGui.QApplication.UnicodeUTF8))
        self.youtubeLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Youtube", None, QtGui.QApplication.UnicodeUTF8))
        self.twitterLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Twitter", None, QtGui.QApplication.UnicodeUTF8))
        self.linkedinLabel_2.setText(QtGui.QApplication.translate("MainWindow", "Linkedin", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteClientButton.setText(QtGui.QApplication.translate("MainWindow", "Delete Client", None, QtGui.QApplication.UnicodeUTF8))
        self.addClientButton.setText(QtGui.QApplication.translate("MainWindow", "Add New Client", None, QtGui.QApplication.UnicodeUTF8))
        self.tabManager.setTabText(self.tabManager.indexOf(self.accountManagerTab), QtGui.QApplication.translate("MainWindow", "Account Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.fetchBt.setText(QtGui.QApplication.translate("MainWindow", "Fetch", None, QtGui.QApplication.UnicodeUTF8))
        self.tabManager.setTabText(self.tabManager.indexOf(self.followersGetter), QtGui.QApplication.translate("MainWindow", "Followers Getter", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArchive.setTitle(QtGui.QApplication.translate("MainWindow", "Archive", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_accounts_data_file.setText(QtGui.QApplication.translate("MainWindow", "Open accounts data file", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDevelopers.setText(QtGui.QApplication.translate("MainWindow", "About BSoD Software", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSocial_Manager_GUI.setText(QtGui.QApplication.translate("MainWindow", "Social Manager - GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

import images_rc
