'''
Initializer for autogenerated GUItest.property

v0.8 -- 10/07/2014 - GUI with listeners
v0.9 -- 10/07/2014 - GUI more funcionality (load clients in a list)
v0.10 -- 11/07/2014 - Helper for file management
v0.11 -- 11/07/2014 - Loadin followers on tableView
'''

from GuiGenerated import Ui_MainWindow
from PySide import QtCore, QtGui
import sys
import json
from helpers import FileHelper
import getFollowers
import string


oldData = { 'twitter' : '',
		 	'facebook' : '',
		 	'linkedin' : '',
		 	'google' : '',
		 	'pinterest' : '',
		 	'youtube' : ''
		}

'''
CLIENT AREA LISTENERS
'''
def listenerClientName(textValue):
	if textValue != "":
		mySW.ui.saveBt.setEnabled(True)
		mySW.ui.pinterestText.setEnabled(True)
		mySW.ui.googleText.setEnabled(True)
		mySW.ui.facebookText.setEnabled(True)
		mySW.ui.linkedinText.setEnabled(True)
		mySW.ui.youtubeText.setEnabled(True)
		mySW.ui.twitterText.setEnabled(True)
		mySW.ui.clientNameText.setEnabled(True)
	else:
		mySW.ui.saveBt.setEnabled(False)
		mySW.ui.pinterestText.setEnabled(False)
		mySW.ui.googleText.setEnabled(False)
		mySW.ui.facebookText.setEnabled(False)
		mySW.ui.linkedinText.setEnabled(False)
		mySW.ui.youtubeText.setEnabled(False)
		mySW.ui.twitterText.setEnabled(False)
		mySW.ui.clientNameText.setEnabled(False)

def listenerSaveButton():

	print "saving..."

'''
SOCIAL AREA LISTENERS
'''
def listenerCheckBoxes():
	if mySW.ui.twitterCk.isChecked() or mySW.ui.googleCk.isChecked() or mySW.ui.facebookCk.isChecked() or mySW.ui.pinterestCk.isChecked() or mySW.ui.youtubeCk.isChecked() or mySW.ui.linkedinCk.isChecked():
		mySW.ui.removeBt.setEnabled(True)
	else:
		mySW.ui.removeBt.setEnabled(False)

def listenerRemoveAccounts():

	print "deleting..."

def listenerEditInfo():

	if mySW.ui.googleText_2.isEnabled() and mySW.ui.facebookText_2.isEnabled() and mySW.ui.pinterestText_2.isEnabled() and mySW.ui.youtubeText_2.isEnabled() and mySW.ui.twitterText_2.isEnabled() and mySW.ui.linkedinText_2.isEnabled():
		
		mySW.ui.editBt.setText('Edit info')

		mySW.ui.googleText_2.setEnabled(False)
		mySW.ui.facebookText_2.setEnabled(False)
		mySW.ui.pinterestText_2.setEnabled(False)
		mySW.ui.youtubeText_2.setEnabled(False)
		mySW.ui.twitterText_2.setEnabled(False)
		mySW.ui.linkedinText_2.setEnabled(False)

		for account in oldData.keys():
			print oldData[account]

		print 'saving....'
	else:
		mySW.ui.editBt.setText('Save edited info')

		mySW.ui.googleText_2.setEnabled(True)
		mySW.ui.facebookText_2.setEnabled(True)
		mySW.ui.pinterestText_2.setEnabled(True)
		mySW.ui.youtubeText_2.setEnabled(True)
		mySW.ui.twitterText_2.setEnabled(True)
		mySW.ui.linkedinText_2.setEnabled(True)

		oldData['twitter'] = mySW.ui.twitterText_2.text()
		oldData['facebook'] = mySW.ui.facebookText_2.text()
		oldData['linkedin'] = mySW.ui.linkedinText_2.text()
		oldData['google'] = mySW.ui.googleText_2.text()
		oldData['pinterest'] = mySW.ui.pinterestText_2.text()
		oldData['youtube'] = mySW.ui.youtubeText_2.text()

def listenerOnClientClicked(item):
	print "Item: " + str(item.text())

	if item:

		data = FileHelper().openReadOnlyJSONFileASObject('data.txt')

		clientSelected = item.text()

		for client in data['clients']:

			if client['name'] == clientSelected:
				accounts = client['accounts']

				if len(accounts) > 0:
					mySW.ui.twitterText_2.setText(accounts[0])
					mySW.ui.youtubeText_2.setText(accounts[1])
					mySW.ui.googleText_2.setText(accounts[2])
					mySW.ui.pinterestText_2.setText(accounts[3])
					mySW.ui.facebookText_2.setText(accounts[4])
					mySW.ui.linkedinText_2.setText(accounts[5])

'''
GET FOLLOWERS AREA LISTENERS
'''

def listenerFetchButton():
	print "fetching"

	tableView = mySW.ui.tableView
	model = QtGui.QStandardItemModel(6, 3, tableView)
	model.setHorizontalHeaderLabels(('Social network', 'Accounts', 'Followers'))

	data = FileHelper().openReadOnlyJSONFileASObject('data.txt')

	i = 0
	for client in data['clients']:
		
		for account in client['accounts']:
			accountData = getFollowers.fetch_for_all_accounts(account)

			print accountData
			if accountData:
				itemNet = QtGui.QStandardItem(accountData[0])
				itemName = QtGui.QStandardItem(accountData[1])
				itemData = QtGui.QStandardItem(accountData[2])

				model.setItem(i, 0, itemNet)
				model.setItem(i, 1, itemName)
				model.setItem(i, 2, itemData)
				i = i+1

	tableView.setModel(model)
	tableView.setColumnWidth(0, 224)
	tableView.setColumnWidth(1, 224)
	tableView.setColumnWidth(2, 224)

def loadClientList():

	data = FileHelper().openReadOnlyJSONFileASObject('data.txt')

	for client in data['clients']:
		mySW.ui.clientListWidget.addItem(client['name'])

class ControlMainWindow(QtGui.QMainWindow):
	def __init__(self, parent=None):
		super(ControlMainWindow, self).__init__(parent)
		self.ui = Ui_MainWindow()
		self.ui.setupUi(self)

	def customSetUp(self):

		loadClientList()

		#Listener for Client name text field
		self.ui.clientNameText.textEdited.connect(listenerClientName)
		#Listener for save client and accounts button
		self.ui.saveBt.clicked.connect(listenerSaveButton)
		#Listeners for checkboxes
		self.ui.linkedinCk.clicked.connect(listenerCheckBoxes)
		self.ui.twitterCk.clicked.connect(listenerCheckBoxes)
		self.ui.facebookCk.clicked.connect(listenerCheckBoxes)
		self.ui.youtubeCk.clicked.connect(listenerCheckBoxes)
		self.ui.pinterestCk.clicked.connect(listenerCheckBoxes)
		self.ui.googleCk.clicked.connect(listenerCheckBoxes)
		#Listener for remove social account
		self.ui.removeBt.clicked.connect(listenerRemoveAccounts)
		#Listener for edit social info accounts
		self.ui.editBt.clicked.connect(listenerEditInfo)
		#Listener client list
		self.ui.clientListWidget.itemClicked.connect(listenerOnClientClicked)
		#LIstener fetch button
		self.ui.fetchBt.clicked.connect(listenerFetchButton)

if __name__ == '__main__':
	app = QtGui.QApplication(sys.argv)
	mySW = ControlMainWindow()
	mySW.customSetUp()
	mySW.show()
	sys.exit(app.exec_())